### ISSUE TITLE
standardize `athenz-sia.env`

### ISSUE THREAD

**Issue by WindzCUHK** [AthenZ/k8s-athenz-sia#40]
`athenz-sia.env` does not contains all the option in [config.go](https://github.com/AthenZ/k8s-athenz-sia/blob/main/pkg/config/config.go)

### some suggestions how this file should be maintained

- has all the options
  - much detail descriptions than `help`
  - default value = value for running in K8s
- important options ONLY
  - required/important options ONLY

**Comment by mlajkim** [comment]
Maybe with the link
```sh
#
# Outputs private key specifically for role certificates (e.g. :true or false)
# default: https://github.com/AthenZ/k8s-athenz-sia/blob/main/pkg/config/default.go#L92
#
ROLE_CERT_KEY_FILE_OUTPUT=true
```
