### ISSUE TITLE
Default values should be carefully selected

### ISSUE THREAD

**Issue by mlajkim** [AthenZ/k8s-athenz-sia#44]
# Background

Default value like `DELETE_INSTANCE_ID=true` is wrong as it requires athenz permission and outputting error message without permission isn't the best 

## TODOs
```
- [ ] Check the default values
- [ ] Check if every env must be modifiable under Makefile
```

**Comment by WindzCUHK** [comment]
Deleting the instance certificate should be the default behavior because of the following:
- improve security
- reduce ZTS load

I think the focus should be the error message.
